Models/kpmobileDBContext.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using MySql.Data.MySqlClient;

namespace WalletWebUtility.Models
{
    [DbConfigurationType(typeof(MySqlConfiguration))]
    public class kpmobileDBContext : DbContext
    {
        public DbSet<device> devices { get; set; }
        public DbSet<MobileLogin> mobilelogin { get; set; }
        public DbSet<MobileAccounts> mobileAccounts { get; set; }
        public kpmobileDBContext()
      : base("name=MyContext")
        {

        }
        public kpmobileDBContext(DbConnection existingConnection, bool contextOwnsConnection)
   : base(existingConnection, contextOwnsConnection)
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            //   modelBuilder.Entity<device>().MapToStoredProcedures();
        }
    }
    [Table("device")]
    public class device
    {
        [Key]
        public string walletno { get; set; }
        public string deviceid { get; set; }
    }
    [Table("mobilelogin")]
    public class MobileLogin
    {
        [Key]
        public string walletno { get; set; }
        public string username { get; set; }
        public string custid { get; set; }
        public string password { get; set; }
        public string pincode { get; set; }
        public string mobileno { get; set; }
        public string emailaddress { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public string birthdate { get; set; }
        public string nationality { get; set; }
        public string natureofwork { get; set; }
        public string provincecity { get; set; }
        public string permanentaddress { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
        public double Version { get; set; }
        public string secquestion1 { get; set; }
        public string secanswer1 { get; set; }
        public string secquestion2 { get; set; }
        public string secanswer2 { get; set; }
        public string secquestion3 { get; set; }
        public string secanswer3 { get; set; }
        public string WalletName { get; set; }


    }
    [Table("mobileaccounts")]
    public class MobileAccounts
    {
        [Key]
        public string walletno { get; set; }
        public decimal balance { get; set; }
        public decimal creditLimit { get; set; }
    }
}

Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WalletWebUtility.Models;

namespace WalletWebUtility.Controllers
{
    public class AuthenticationController : Controller
    {
        // GET: Authentication
        public ActionResult Index()
        {
            return View();
        }
        //POST : Login user authentication
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult UserAuthentication(MobileLogin login)
        {
            if (ModelState.IsValid)
            {
                using (kpmobileDBContext db = new kpmobileDBContext())
                {
                    var response = db.mobilelogin.Where(s => s.username.Equals(login.username) && s.password.Equals(login.password)).FirstOrDefault();
                    if (response != null)
                    {
                        Session["Username"] = response.username.ToString();
                        return RedirectToAction("Index", "Home");
                    }
                }


            }

            return View(login);

        }
    }
}

Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WalletWebUtility.Models;

namespace WalletWebUtility.Controllers
{
    public class DeviceController : Controller
    {
        private kpmobileDBContext db = new kpmobileDBContext();
        // GET: Device
        public ActionResult Index()
        {
            var returnview = db.devices.ToList();          
            return View(returnview);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WalletWebUtility.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/WalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WalletWebUtility.Models;

namespace WalletWebUtility.Controllers
{
    public class WalletController : Controller
    {
        private kpmobileDBContext db = new kpmobileDBContext();
        // GET: Wallet
        public ActionResult Index(string PageSize, string searchString)
        {
            int a = Convert.ToInt32(String.IsNullOrEmpty(PageSize) ? "10" : PageSize);
            var returnview = db.mobilelogin.ToList().Take(a);
            if (!String.IsNullOrEmpty(searchString))
            {
                returnview = db.mobilelogin.Where(s => s.walletno.Contains(searchString));
            }
            return View(returnview);
        }
        public ActionResult IndexSort(string PageSize)
        {
            int a = Convert.ToInt32(String.IsNullOrEmpty(PageSize) ? "10" : PageSize);
            var returnview = db.mobilelogin.ToList().Take(a);
            return PartialView("~/Views/Wallet/_WalletUsersTable.cshtml", returnview);
        }
       
    }
}

Views/Authentication/Index.cshtml
@model WalletWebUtility.Models.MobileLogin

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MLWallet Web Utility Authentication</title>


    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")

</head>
<body>
    <div class="wrapper row-custom">
        <div class="position-relative header-wrapper">
            <div class="Authentication-header width-full">
                <div class="container-Authentication-header width-full text-center">
                    <a href="https://github.com/"> <img src="~/Content/mlhuillierlogo.png" alt="mlhuillierlogo" width="300" height="75"></a>
                </div>

            </div>
        </div>

        <div class="Authentication-main">
            <div class="Authentication-container">
                @using (Html.BeginForm("UserAuthentication", "Authentication", FormMethod.Post))
                {
                    <div class="Authentication-form-body mt-3">
                        <div class="Authentication-form-header">
                            <h5>Sign in to Wallet Web Utility</h5>
                        </div>

                        <div class="card " style="width: 18rem;">
                            <div class="card-body">
                                <label>Username</label>

                                @Html.TextBox("UserName", "", new { @class = "form-control", @id = "txtloginusername" })
                                @* <input type="text" name="name" value="" class="form-control" /> *@
                                <label style="margin-top:5%;">
                                    Password
                                    <a class="label-link" href="/password_reset">Forgot password?</a>
                                </label>
                                @Html.Password("Password", "", new { @class = "form-control", @id = "txtpassword" })

                                <input type="submit" name="name" value="Sign In" class="btn btn-success form-control" style="margin-top:5%;" />
                            </div>
                        </div>
                    </div>
                }


            </div>
        </div>

        @*  *@

    </div>
    @Scripts.Render("~/bundles/customScripts")
    @Scripts.Render("~/bundles/scripts")
</body>
</html>

Views/Device/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/ContentLayout.cshtml";
}

@model IEnumerable<WalletWebUtility.Models.device>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/ContentLayout.cshtml";
}

<div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
        <h4 class="card-header">Wallet Public Devices</h4>
        <div class="from-group row">

            <div class="col-sm-12" style="float:left;">
                <input type="text" name="name" value="" class="form-control" placeholder="Search Wallet Number" />
            </div>
        </div>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.walletno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.deviceid)
                </th>
                <th>Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.walletno)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.deviceid)
                    </td>
                    <td>
                        @Html.ActionLink("Details ", "Details", new { id = item.walletno }, new { @class = "btn btn-info" })

                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Views/Device/Index.cshtml
@model IEnumerable<WalletWebUtility.Models.device>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/ContentLayout.cshtml";
}

<div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
        <h4 class="card-header">Wallet Public Devices</h4>
        <div class="from-group row">

            <div class="col-sm-12" style="float:left;">
                <input type="text" name="name" value="" class="form-control" placeholder="Search Wallet Number" />
            </div>
        </div>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.walletno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.deviceid)
                </th>
                <th>Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.walletno)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.deviceid)
                    </td>
                    <td>
                        <button value="@item.walletno" class="btn btn-danger" id="btnModalDlt">
                            Delete
                        </button>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>
@Html.Partial("~/Views/Device/_ModalCfrDlt.cshtml");

Views/Device/_ModalCfrDlt.cshtml
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you absolutely sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="alert alert-warning" role="alert">
                Unexpected bad things will happen if you don’t read this!
            </div>
            <div class="modal-body">
                <p>
                    This action
                    <strong style="color:black;">cannot</strong> be undone.
                    This will permanently delete the <strong class="WalletNumber" style="color:black;">
                    </strong><strong style="color:black;"> DEVICE </strong>
                </p>
                <p>
                    Please type <strong class="WalletNumber" style="color:black;"></strong> to confirm.
                </p>
            </div>
            <div class="modal-footer">
                <div class="col-sm-12">
                    <input type="text" name="" value="" class="form-control" style="margin-bottom:2.5px;" id="txtDeleteDevice" />
                    <button value="" id="btnDeleteDevice" class="btn btn-danger form-control " style="margin-top:2.5px;">
                        I understand the consequences, delete this repository
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        @if (Session["Username"] != null)
        {
            <h1>@Session["Username"].ToString()</h1>
        }
    </div>
</body>
</html>

Views/Shared/ContentLayout.cshtml
@{
    ViewBag.Title = "ContentLayout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    @Html.ActionLink("View Users", "Index", "Wallet",null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Remove Device", "Index", "Device",null, new { @class = "nav-link" })
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Page</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
                @RenderBody()
        </div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>    <!-- Bootstrap CSS CDN -->


    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")


</head>
<body>
    <div class="wrapper">

        <nav id="sidebar">
            <div class="sidebar-header row-custom" style="">

                <button type="button" id="sidebarClose" class="btn ">
                    <i class="fa fa-align-justify"></i>
                </button>
                <button type="button"  class="btn" style="padding-left:0px;">
                    <img src="~/Content/mlhuillierlogo.png" alt="mlhuillierlogo" width="175" height="50">
                </button>
                


            </div>


            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Applications</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            @Html.ActionLink("ML Wallet Public", "Index", "Wallet")
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </nav>
        <div id="content">
            <div class="main-header row">

                <button type="button" id="sidebarOpen" class="btn" style="margin-left:10px;">
                    <i class="fa fa-align-justify"></i>
                </button>



                <button type="button"  class="btn " style="padding-left:0px;">
                    <img src="~/Content/mlhuillierlogo.png" alt="mlhuillierlogo" width="175" height="50">
                </button>
               

            </div>


            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
        <div class="overlay"></div>
    </div>

    @Scripts.Render("~/bundles/customScripts")
    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)

</body>
</html>

Views/Shared/_LayoutSub.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Wallet/Index.cshtml
@model IEnumerable<WalletWebUtility.Models.MobileLogin>

@{
    ViewBag.Title = "ML Wallet Public - Wallet Users";
    Layout = "~/Views/Shared/ContentLayout.cshtml";
}
<div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
        <h4 class="card-header">Wallet Public Users</h4>
        @using (Html.BeginForm("Index", "Wallet", FormMethod.Get))
        {
            <div class="from-group row">

                <div class="col-sm-2" style="padding-right:5px;">

                    @Html.DropDownList("PageSize", new List<SelectListItem> {
                new SelectListItem{ Text="1",Value="1"},
                new SelectListItem{ Text="10",Value="10"},
                new SelectListItem{ Text="50",Value="50"},
                new SelectListItem{ Text="100",Value="100"}
                }, new { @class = "form-control input-sm", @id = "drpsort" })

                </div>

                <div class="col-sm-8" style="float:left; padding-left:0px;">
                    <input type="text" name="searchString" value="" class="form-control" placeholder="Search Wallet Number" />
                </div>
                <div class="col-sm-2">
                    <input type="submit" value="Filter" class="btn btn-default" />
                </div>

            </div>
        }
      
    <div id="himohimoniIan">
        @Html.Partial("~/Views/Wallet/_WalletUsersTable.cshtml", Model);
    </div>
     
    </div>
</div>
@*<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="loadingModalniIan" data-backdrop="static">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
                Loading...           
        </div>
    </div>
</div>*@

Views/Wallet/_WalletUsersTable.cshtml
@model IEnumerable<WalletWebUtility.Models.MobileLogin>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.walletno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.walletno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.ActionLink("Details ", "Details", new { id = item.walletno }, new { @class = "btn btn-info" })

            </td>
        </tr>
    }
</table>